- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt: name={{ item }}
  with_items:
    - autoconf
    - git
    - subversion
    - curl
    - bison
    - imagemagick
    - libmagickwand-dev
    - build-essential
    - libmariadbclient-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - zlib1g-dev
    - python-software-properties

- name: add redmine group
  group: name=redmine system=yes

- name: add redmine user
  user: name=redmine shell=/bin/bash home=/opt/redmine group=redmine system=yes

- name: cloning rbenv
  git: repo=git://github.com/sstephenson/rbenv.git accept_hostkey=yes dest=/opt/redmine/.rbenv version=master

- name: cloning ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git accept_hostkey=yes dest=/opt/redmine/.rbenv/plugins/ruby-build version=master

- name: setting owner and group for .rbenv directory
  file: path=/opt/redmine/.rbenv recurse=yes owner=redmine group=redmine

- name: adding rbenv to $PATH
  shell: su - redmine -c "echo 'export PATH=\"\$HOME/.rbenv/bin:\$PATH\"' >> ~/.bash_profile"

- name: adding rbenv initialization to .bash_profile
  shell: su - redmine -c "echo 'eval \"\$(rbenv init -)\"' >> ~/.bash_profile"

- name: installing ruby 2.1.2
  shell: su - redmine -c "rbenv install -f 2.1.2"

- name: setting as global ruby 2.1.2
  shell: su - redmine -c "rbenv global 2.1.2"

- name: cloning redmine 2.6-stable
  git: repo=https://github.com/redmine/redmine.git accept_hostkey=yes dest=/opt/redmine/redmine version=2.6-stable

- name: setting true rules
  file: path=/opt/redmine/redmine/{{ item.path }} owner=redmine group=redmine mode=0755 recurse=yes state=directory
  with_items:
    - { path: 'tmp' }
    - { path: 'tmp/pids' }
    - { path: 'tmp/sockets' }
    - { path: 'public/plugin_assets' }
    - { path: 'files' }
    - { path: 'log' }

- name:
  template: src=config/puma.rb dest=/opt/redmine/redmine/config/puma.rb owner=redmine group=redmine mode=0600