- hosts: redmine-test
  remote_user: deploy
  gather_facts: no
  sudo: yes

  vars_prompt:

    - name: redmine_db_database
      prompt: Enter Redmine database name
      private: no

    - name: redmine_db_host
      prompt: Enter Redmine database host
      private: no

    - name: redmine_db_username
      prompt: Enter Redmine database username
      private: no

    - name: redmine_db_password
      prompt: Enter Redmine database password
      private: yes
      confirm: yes

  roles:
    - build-docker-image
    - deploy-redmine