- name: make temp directory for Dockerfile
  file:
    path=deploy/temp
    mode=0700
    state=directory

- name: copy Dockerfile to temp directory
  template:
    src=postgresql/Dockerfile
    dest=deploy/temp/
    mode=0700

- name: build an image
  docker_image:
    path=deploy/temp
    name=postgresql
  sudo: yes

- name: remove temp directory for Dockerfile
  file:
    path=deploy
    state=absent

- name: start docker container
  docker:
    image=postgresql
    ports=5432:5432
    state=running
  sudo: yes